import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar/navbar";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-in",
});
export const cx = (...classNames) => classNames.filter(Boolean).join(" ");
const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mr",
});

export const metadata = {
  title: "Fast Food",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cx(
        inter.variable,
        manrope.variable,
        "font-mr bg-light"
      )}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}